/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.opcionesControlador;
import Controlador.preguntasControlador;
import Modelo.opciones;
import Modelo.preguntas;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import javax.swing.JOptionPane;

/**
 *
 * @author santiago
 */
public class Preguntas extends javax.swing.JFrame {
    
int rondanum=0;
opcionesControlador oC=new opcionesControlador();
    public Preguntas() {
        initComponents();
        
        rondanum+=1;
        preguntasControlador pC= new preguntasControlador();
        labelTituloPreg.setText("Ronda :"+String.valueOf(rondanum));//pARA LA RONDA
        String pregunta= pC.generarPregunta();//Para la pregunta
        labelPregunta.setText(pregunta);
        preguntas pr=new preguntas(pC.getIdpreguntamomento(),rondanum,pC.generarPregunta());
        //para las opciones
        opcionesControlador oC=new opcionesControlador();
        String[] op;
        op = oC.generarOpciones(pr.getId());
        String opC;
        opC=oC.generarRespuestaCorrecta(pr.getId());
        rb1.setText(op[0]);
        rb2.setText(op[1]);
        rb3.setText(op[2]);
        rb4.setText(op[3]);
        
        
        }

        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnEnviar = new javax.swing.JButton();
        labelTituloPreg = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        labelPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        labelTituloPreg.setText("Ronda");

        buttonGroup1.add(rb1);
        rb1.setText("jRadioButton1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setText("jRadioButton2");

        buttonGroup1.add(rb3);
        rb3.setText("jRadioButton3");

        buttonGroup1.add(rb4);
        rb4.setText("jRadioButton4");

        labelPregunta.setText("Pregunta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTituloPreg)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb4)
                            .addComponent(rb3)
                            .addComponent(rb2)
                            .addComponent(rb1)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(labelPregunta)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloPreg)
                .addGap(35, 35, 35)
                .addComponent(labelPregunta)
                .addGap(39, 39, 39)
                .addComponent(rb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        opcionesControlador oC=new opcionesControlador();
        preguntasControlador pC= new preguntasControlador();
        preguntas pr=new preguntas(pC.getIdpreguntamomento(),rondanum,pC.generarPregunta());
        String[] op;
        op = oC.generarOpciones(pr.getId());
        String opC;
        opC=oC.generarRespuestaCorrecta(pr.getId());
        int indice = oC.validarSeleccion(op,opC);
        if(rb1.isSelected()){
            if(op[0].equals(opC))
                JOptionPane.showMessageDialog(null,"Respuesta correcta");
            else
                JOptionPane.showMessageDialog(null,"Respuesta incorrecta");
        }else if(rb2.isSelected()){
            if(op[1].equals(opC))
               JOptionPane.showMessageDialog(null,"Respuesta correcta");
            else
                JOptionPane.showMessageDialog(null,"Respuesta incorrecta"); 
        }else if(rb3.isSelected()){
            if(op[2].equals(opC))
                JOptionPane.showMessageDialog(null,"Respuesta correcta");
            else
                JOptionPane.showMessageDialog(null,"Respuesta incorrecta");
        }else if(rb4.isSelected()){
            if(op[3].equals(opC))
                JOptionPane.showMessageDialog(null,"Respuesta correcta");
            else
                JOptionPane.showMessageDialog(null,"Respuesta incorrecta");
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JLabel labelTituloPreg;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    // End of variables declaration//GEN-END:variables
}
